Updated resources

diff --git a/resources/pre-push b/resources/pre-push
--- a/resources/pre-push
+++ b/resources/pre-push
@@ -1,17 +1,7 @@
 #!/bin/bash
 
 # Run RSpec, yarn lint, and rubocop before pushing
-echo "Running Rubocop..."
-echo "###############################"
-bundle exec rubocop
-if [ $? -ne 0 ]; then
-  echo -e "\e[31m\nFAILURE: Your Rubocop tests have failed\e[0m"
-  exit 1
-else
-  echo -e "\e[32m\nSUCCESS: Your Rubocop tests were successful\e[0m"
-fi
-
-echo -e "\nRunning esLint..."
+echo "\nRunning esLint..."
 echo "###############################"
 yarn lint
 if [ $? -ne 0 ]; then
@@ -19,6 +9,16 @@ if [ $? -ne 0 ]; then
   exit 1
 else
   echo -e "\e[32m\nSUCCESS: Your esLint tests were successful\e[0m"
+fi
+
+echo -e "Running Rubocop..."
+echo "###############################"
+bundle exec rubocop
+if [ $? -ne 0 ]; then
+  echo -e "\e[31m\nFAILURE: Your Rubocop tests have failed\e[0m"
+  exit 1
+else
+  echo -e "\e[32m\nSUCCESS: Your Rubocop tests were successful\e[0m"
 fi
 
 # echo -e "\nRunning RSpec..."
